title: Camille Kaye Ochoa
logo: /img/character.jpg
description: Hello prospective employers! My name is Camille/Kaye. I love automating things and I am currently learning about embedded software. I was in IT Support previously and I love it, I like everything in technology. My goal is to become an Embedded Software Engineer, where I can demonstrate my skills and learn more about Software Engineering so welcome to my portfolio website, and see the things that I'm currently working on, I can't wait to talk to you about it.
show_downloads: true
github:
  zip_url: /img/resume.pdf
  tar_url: http://linkedin.com/in/ochoack
theme: jekyll-theme-minimal
